### ISSUE TITLE
Send to Readwise does not render for reddit on firefox

### ISSUE THREAD

**Issue by devjones** [marcus-crane/comments-to-readwise#8]
I've confirmed the "Send to readwise" button shows up on Chrome.  It doesn't appear in firefox however.

Confirmed working for HackerNews on firefox.

**Comment by devjones** [comment]
I'm using the manual install option from https://github.com/marcus-crane/comments-to-readwise#firefox-users

Maybe this will auto-resolve when Firefox supports Manifest v3?

**Comment by marcus-crane** [comment]
Hi there,

I'm not sure I understand the scope of the issue since your message is a bit contradictory 😅

You said it does work for Hacker News using Firefox, which would imply the button does appear.

Do you mean that other sites besides HN are working in Chrome but not Firefox?

**Comment by devjones** [comment]
My title was inaccurate. It does not render for Reddit on Firefox.  Other tests passed

**Comment by marcus-crane** [comment]
Ah ok, I'll have a look 🙂

**Comment by marcus-crane** [comment]
Oh! I had forgotten about the state of this extension a bit since I wasn't aware of anyone else actually using it.

At one point, I rewrote it to be easier to extend to new sites going but I hadn't actually ported over the Reddit code: https://github.com/marcus-crane/comments-to-readwise/blob/main/src/content-scripts/sites/reddit-old.ts

The reason it doesn't work is because there's no code for it to execute hah.

It should be easy enough to port over though. The reason it works in Chrome is because that's technically running an older version as there is no automatic update process set up for this extension (yet)

**Comment by marcus-crane** [comment]
Hi there,

I've reintroduced the parsing code for old.reddit.com and rewritten it slightly to use the Reddit API instead of extracting content from the page

You can find the latest release for Firefox as an XPI here: https://github.com/marcus-crane/comments-to-readwise/releases/tag/2.1.0

It'll probably be a week or two until you can just install from the store and get auto updates due to the holiday closedowns

**Comment by devjones** [comment]
> I wasn't aware of anyone else actually using it.

Thanks again for the quick fix.  And I recommend you make a Show HN post once the firefox extension is approved.  I think lots of people would like to archive insightful comments on HN/reddit as well.  My flow is comments -> readwise -> obsidian.
